[![Rust](https://github.com/Tootnbarbs/solana-security-txt/actions/workflows/rust.yml/badge.svg)](https://github.com/Tootnbarbs/solana-security-txt/actions/workflows/rust.yml)https://github.com/Tootnbarbs/solana-security-txt/actions/workflows/rust.yml/badge.svghttps://github.com/Tootnbarbs/solana-security-txt/actions/workflows/rust.ymlname: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
